title: Benchoff Design Portfolio
description: Design Portfolio
theme: jekyll-theme-minimal
repository: bbenchoff/bbenchoff.github.io
github:
  is_project_page: true
  repository_url: https://github.com/bbenchoff/bbenchoff.github.io

baseurl: ""
url: ""

# Define default layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "system7"
    values:
      layout: "system7"

includes: ['system7']
defaults:
  -
    scope:
      path: "system7"
    values:
      layout: "system7"