title: "Brian Benchoff - Hardware Engineering & PCB Design Portfolio"
description: "Hardware engineering projects, PCB design, and reverse engineering by Brian Benchoff. Specializing in embedded systems, electronics, and innovative hardware solutions."
author: "Brian Benchoff"
theme: jekyll-theme-minimal
repository: bbenchoff/bbenchoff.github.io
url: "https://bbenchoff.github.io"
baseurl: ""

# SEO Optimization
twitter:
  username: "@bbenchoff"
  card: summary_large_image

# Plugin Settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Site Settings
github:
  is_project_page: true
  repository_url: https://github.com/bbenchoff/bbenchoff.github.io

baseurl: ""
url: ""

# Define default layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "system7"
    values:
      layout: "system7"

includes: ['system7']
defaults:
  -
    scope:
      path: "system7"
    values:
      layout: "system7"