theme: jekyll-theme-minimal


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      
  author:
  name: "Brian Benchoff"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "No"
  location: "SF"
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"
